# Generated by Django 2.0.2 on 2018-02-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_likeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeprofile',
            name='like_user',
        ),
        migrations.RemoveField(
            model_name='likeprofile',
            name='profile_ptr',
        ),
        migrations.DeleteModel(
            name='LikeProfile',
        ),
    ]
